// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

//  Example 2:
// Input: s = "", t = "y"
// Output: "y"
  
// Example 3:
// Input: s = "a", t = "aa"
// Output: "a"
  
// Example 4:
// Input: s = "ae", t = "aea"
// Output: "a"
 
// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lower-case English letters.
_________________________________________________________________________________________________
class Solution {
    public char findTheDifference(String s, String t) {
        HashMap<Character,Integer> hm=new HashMap<>();
        
        for(int i=0;i<s.length();i++){
            char c=s.charAt(i);
            hm.put(c,hm.getOrDefault(c, 0)+1);
        }
        for(int i=0;i<t.length();i++){
             char c=t.charAt(i);
            if(!hm.containsKey(c) || hm.get(c)==0)
                return c;
            else
                hm.put(c,hm.get(c)-1);
                
        }
        return ' ';
        
    }
}
 
